title: Alejandro Jair García
logo: /assests/img/Alex_img.png
description: Soy un apasionado científico de datos con experiencia en análisis, visualización, modelado y predicción de datos. Mi prioridad es la transformación de datos en conocimiento significativo, para la toma de decisiones informadas y con conocimiento científico.
También soy un entusiasta de la naturaleza y el trekking, lo que me inspira a seguir explorando y aprendiendo constantemente.
#show_downloads: true
theme: jekyll-theme-minimal
