title: Alejandro Jair García
logo: /assets/img/Alex_circle_red.png
description: >
  Soy un apasionado científico de datos con experiencia en análisis, visualización y predicción, que busca transformar los datos en conocimiento significativo para decisiones informadas.
  
  Entusiasta de la naturaleza y el trekking.
#show_downloads: true
theme: jekyll-theme-minimal
