title: Alejandro J. García
logo: /assets/img/Alex_circle_red.png
description: >
  Soy un apasionado científico de datos con experiencia en análisis, visualización y predicción.
  Mi objetivo es transformar datos en conocimiento significativo para la toma de decisiones informadas.
#show_downloads: true
theme: jekyll-theme-minimal
