title: Alejandro J. García
logo: /assets/img/Alex_circle_red.png
description: >
  I am passionate about data with expertise in analytics, visualization, and forecasting.
  My goal is to transform data into meaningful knowledge for data-driven decision making.
#show_downloads: true
theme: jekyll-theme-minimal
